name: 'npm Bump Version'
description: 'Increase npm version'
outputs:
  current-version:
    description: 'Current new version after Bump Version'
    value: ${{ steps.npmBumpVersion.outputs.currentVersion }}
runs:
  using: "composite"
  steps:
    - id: npmBumpVersion
      name: NPM Bump Version
      shell: bash
      run: |
        npm config set git-tag-version false
        npm config set commit-hooks false
        newVersion=`npm version patch`
        echo "The version has been successfully increased to $newVersion"
        echo "::set-output name=currentVersion::${newVersion#v}"
