name: 'Post Bump Version'
description: 'Commit the Bumped version'
inputs:
  gh-user-name:
    description: GITHUB User name to be used in git config --global user.name "Your Name"
    required: true
  gh-user-email:
    description: GITHUB User email to be used in git config --global user.email "you@example.com"
    required: true
  commit-message-prefix:
    description: 'Text for commit message prefix. Fallback is RC:'
    required: false
  commit-message-fallback:
    description: 'Message used to bump version commit'
    required: false
    default: No commit message
  skip-ci:
    description: 'Flag to skip-ci after push'
    required: false
runs:
  using: "composite"
  steps:
    - id: commitBumpedVersion
      name: Commit Bumped Version
      shell: bash
      run: |
        commitMessage=${{ github.event.head_commit.message }} || ${{ inputs.commit-message-fallback }}
        if [ "${{inputs.commit-message-prefix}}" ]
        then
          commitMessage="${{inputs.commit-message-prefix}}$commitMessage"
        fi
        if [ "${{inputs.skip-ci}}" ]
        then
          commitMessage="[no-ci] $commitMessage"
        fi
        git config --global user.name '${{ inputs.gh-user-name }}'
        git config --global user.email '${{ inputs.gh-user-email }}'
        git add package.json package-lock.json
        git commit -m $(echo "${commitMessage}")
        git pull
        git push
        echo "The RC version has been successfully committed"
