name: Show Object
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  gh-object:
    name: Show GH object
    runs-on: ubuntu-latest
    steps:
      - id: show-gh-object
        name: Show github object
        run: |
          echo "${{github}}"
  commit-message:
    name: Show the last commit message
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout current repository
        uses: actions/checkout@v3
      - id: show-last-commit
        name: Show last commit
        run: |
          echo $(git log -1 --format='%s')
