name: Playground
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  check-gh-objects:
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'
      - name: showGithubActorName
        run: |
          echo '${{secrets.GITHUB_ACTOR}}'
      - name: showActorUserObject
        run: |
          userAPIData=${{fromJson($(gh api -H "Accept: application/vnd.github+json" /users/${{github.actor}}))}}
          echo '${{toJson(userAPIData)}}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
