name: Playground
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  check-gh-objects:
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'
      - id: getUserObject
        name: Get user from gh API
        run: |
          USER_DATA=`gh api -H "Accept: application/vnd.github+json" /users/${{github.actor}}`
          echo "::set-output name=userJson::$USER_DATA"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: showUserObject
        run: |
          echo '${{toJson(fromJson(steps.getUserObject.userJson))}}'
