name: Playground
on:
  push:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.22.3]
    steps:
      - id: checkout
        name: Checkout current repository
        uses: actions/checkout@v3
      - id: setupEnv
        name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - id: bumpVersion
        name: Bump APP Version
        uses: ./.github/actions/npm-bump-version
      - id: showCurrentAppVersion
        name: Show current APP Version
        run: |
          echo "Current Version: ${{steps.bumpVersion.outputs.current-version}}"
      - id: install
        name: Install packages
        run: npm ci


  get-user-data:
    name: Get user data to config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: getUserNameAndEmail
        name: Get user config name and email
        uses: ./.github/actions/get-actor-user-data
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: show-actor-user-data
        name: Show actor user data
        run: |
          echo "Name: ${{steps.getUserNameAndEmail.outputs.name}}"
          echo "Email: ${{steps.getUserNameAndEmail.outputs.email}}"
