name: Playground
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  check-gh-objects:
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'

      - id: fetchUserEvents
        name: Fetch user's public events
        run: |
          gh api -H "Accept: application/vnd.github+json" /users/${{github.actor}}/events/public >> ./user-events.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: getUserEvents
        name: Parse user's events
        run: |
          # echo "::set-output name=userEvents::"$(jq '.' ./user-events.json)
          echo "::set-output name=userEvents::"$(readarray -t values < <(jq -r '.[]' ./user-events.json))

      - id: getUserNameAndEmail
        name: Get user config name and email
        run: |
          userEvents=${{steps.getUserEvents.outputs.userEvents}}
          echo "$userEvents"
          userName=null
          userEmail=null
          echo "$userEvents[0]"
          echo $userEvents[0]
          echo ${userEvents[0]}
          i=0
          echo "$userEvents[$i]"
          while [$userEvents[$i]]
          do
            echo $userEvents[$i].payload.commits.author
            $i = $i + 1
          done
