name: Playground
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  check-gh-objects:
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'
      - id: getUserPublicEvents
        name: Fetch user's public events page
        run: |
          echo 'JSON_RESPONSE<<EOF' >> ././temp.json
          gh api -H "Accept: application/vnd.github+json" /users/${{github.actor}}/events/public >> ./temp.json
          echo 'EOF' >> ./temp.json
          USER_EVENTS=`cat ./temp.json`
          echo "::set-output name=userEvents::$USER_EVENTS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: getUserNameAndEmail
        name: Get user config name and email
        run: |
          userEvents=${{fromJson(steps.getUserPublicEvents.outputs.userEvents)}}
          userName=null
          userEmail=null
          i=0
          while [[-z "$userEmail"] && ["$userEvents[$i]"]]
          do
            echo $userEvents[$i].payload.commits.author
            $i = $i + 1
          done
