name: Playground
on:
  push:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  show-gh-object:
    name: Show gh object
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'

  get-user-data:
    name: Get user data to config
    runs-on: ubuntu-latest
    steps:
      - id: getUserNameAndEmail
        name: Get user config name and email
        uses: ./.github/actions/get-actor-user-data
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: show-actor-user-data
        name: Show actor user data
        run: |
          echo "Name: ${{steps.getUserNameAndEmail.outputs.name}}"
          echo "Email: ${{steps.getUserNameAndEmail.outputs.email}}"
