name: Playground
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  check-gh-objects:
    runs-on: ubuntu-latest
    steps:
      - name: showGithubContextObject
        run: |
          echo '${{toJson(github)}}'
      - name: showSecrets
        run: |
          echo '${{secrets}}'
      - name: showActorUserObject
        run: |
          USER_DATA=$(gh api -H "Accept: application/vnd.github+json" /users/${{github.actor}})
          echo -e $USER_DATA
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
